# Generated by Django 3.2.7 on 2021-10-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countorder',
            name='ordercount',
        ),
        migrations.AddField(
            model_name='countorder',
            name='ordercount',
            field=models.ManyToManyField(related_name='orders', to='cars_ecom.Orders'),
        ),
    ]
