# Generated by Django 3.2.7 on 2021-10-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ecom', '0002_auto_20211006_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountOrder',
        ),
    ]
