# Generated by Django 3.2.7 on 2021-10-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ecom', '0004_alter_orders_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extended_orders',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='extended_orders',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='orders',
            name='cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_items', to='cars_ecom.cars'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
