# Generated by Django 3.2.7 on 2021-10-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_ecom', '0005_auto_20211007_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_items', to='cars_ecom.clients'),
        ),
    ]
